export * from './lib/prime-components.module';
export * from './lib/button';
export * from './lib/icon';
export * from './lib/loading-indicator';
export * from './lib/dialog';
export * from './lib/input-text';
export * from './lib/input-textarea';
export * from './lib/input-date';
export * from './lib/dropdown';